# Generated by Django 5.0.2 on 2024-03-03 20:15

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='email',
        ),
        migrations.AddField(
            model_name='entrada',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2024, 3, 3, 20, 15, 12, 272184, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrada',
            name='cajero',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='contador.cajero'),
            preserve_default=False,
        ),
    ]
