# Generated by Django 5.0.2 on 2024-02-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='valorEntrada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
