# Generated by Django 5.0.2 on 2024-02-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_alter_caja_valorentrada_alter_entrada_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='caja',
        ),
        migrations.DeleteModel(
            name='Caja',
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
    ]
